#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL=${DATABASE_PG_URL}
export REDIS_URL=${REDIS_URL}

echo "Database host address: ${DATABASE_URL}"
echo "Redis host address: ${REDIS_URL}"

postgres_ready() {
python << END
import sys

from sqlalchemy.ext.asyncio import AsyncEngine

try:
    create_async_engine(${DATABASE_URL})
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

redis_ready() {
python << END
import sys

import redis

try:
    conn = redis.StrictRedis(
        host="${REDIS_HOST}",
        port="${REDIS_PORT}",
        db="${REDIS_DB}",
    )
    conn.ping()
except redis.exceptions.ConnectionError:
    sys.exit(-1)
sys.exit(0)

END
}
until redis_ready; do
  >&2 echo 'Waiting for Redis to become available...'
  sleep 1
done
>&2 echo 'Redis is available'

exec "$@"
